# {{ ansible_managed }}
#FROM        debian:jessie
#FROM        stackbrew/ubuntu:14.04
FROM        jasongiedymin/ansible-base-ubuntu

# Volume can be accessed outside of container
VOLUME      [{{ docker_volume_directory }}]

MAINTAINER  Alban Andrieu "https://github.com/AlbanAndrieu"

ENV			DEBIAN_FRONTEND noninteractive
ENV         JBOSS_HOME {{ jboss_home_dir }}
ENV         WORKDIR /home/vagrant

# Working dir
WORKDIR {{ docker_working_directory }}

# COPY
#COPY

RUN         pwd
RUN         ls -lrta

# ADD
ADD defaults $WORKDIR/ansible-zap/defaults
ADD meta $WORKDIR/ansible-zap/meta
ADD files $WORKDIR/ansible-zap/files
ADD handlers $WORKDIR/ansible-zap/handlers
ADD tasks $WORKDIR/ansible-zap/tasks
ADD templates $WORKDIR/ansible-zap/templates
#ADD vars $WORKDIR/ansible-zap/vars

# Here we continue to use add because
# there are a limited number of RUNs
# allowed.
ADD hosts /etc/ansible/hosts
ADD jboss.yml $WORKDIR/ansible-jboss/jboss.yml

# Execute
RUN         pwd
RUN         ls -lrta
RUN         ansible-playbook $WORKDIR/ansible-jboss/jboss.yml -c local -vvvv

#RUN         apt-get update && \
#            apt-get install -y openssh-server openjdk-7-jre-headless
#RUN         useradd -m -s /bin/bash jenkins
#RUN         echo jenkins:jenkins | chpasswd
#RUN         mkdir -p /var/run/sshd
            
EXPOSE 21:9999
ENTRYPOINT  ["/etc/init.d/jboss", "start"]
CMD ["-g", "deamon off;"]
